# generated by datamodel-codegen:
#   filename:  slack_url_verification.json
#   timestamp: 2024-04-28T11:43:03+00:00

from __future__ import annotations

from typing_extensions import TypedDict


class Model(TypedDict):
    token: str
    challenge: str
    type: str
