name: Carrier Owl

on:
  schedule:
    # 時刻: 9:59 (UTC) == 18:59(JST, UTC+9)
    # 曜日: 日曜日(0)、水曜日(3)、木曜日(4)、金曜日(5)、土曜日(6)
    - cron: "59 9 * * 0,3,4,5,6"
  workflow_dispatch:

  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run image
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: 1.8.2

      - name: install dependencies
        run: poetry install

      - name: Run owl
        run: poetry run task fly
        env:
          DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}
          SLACK_ID: ${{ secrets.SLACK_ID }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
