name: Setup

on:
  push:
    branches:
      - main
      - master

jobs:
  # poetry.lock が変更されたときに requirements.txt を自動更新する
  setup:
    runs-on: ubuntu-latest
    env:
      file_changed: "false"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 履歴はすべてフェッチする

      # push の前後で poetry.lock が変更されたかどうかを確認する
      - name: Check for changes in poetry.lock
        id: check_change
        run: |
          git diff --quiet ${{ github.event.before }} ${{ github.sha }} -- poetry.lock || echo "file_changed=true" >> $GITHUB_ENV

      # 以降のステップは poetry.lock が変更されたときのみ実行する
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        if: env.file_changed == 'true'

      - name: Run image
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: 1.8.2
        if: env.file_changed == 'true'

      - name: Make requirements.txt
        run: poetry export -f requirements.txt --output src/requirements.txt
        if: env.file_changed == 'true'

      - name: Insert comment to requirements.txt
        run: |
          sed -i '1i # GSF 用に main.py と同じディレクトリに配置しているファイルです。' src/requirements.txt
        if: env.file_changed == 'true'

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update requirements.txt
        if: env.file_changed == 'true'
