name: Setup # 今は requirements.txt を自動更新するだけ

on:
  push:
    branches:
      - main
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run image
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: 1.8.2

      - name: Make requirements.txt
        run: poetry export -f requirements.txt --output src/requirements.txt

      - name: Insert comment to requirements.txt
        run: |
          sed -i '1i # GSF 用に main.py と同じディレクトリに配置しているファイルです。' src/requirements.txt

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update requirements.txt
